### ISSUE TITLE
[Question] How effictive is this mod now?

### ISSUE THREAD

**Issue by LarveyOfficial** [nodusclient/gaslight#3]
Lots have changes have been done since rc1, I belive it is now on rc4 and I was wondering how effective this is after the changes.
I know mojang now tracks if a message is "Secure", although I don't know how effective it is.

So I was just wondering how effective is the mod right now?

**Comment by KMikeeU** [comment]
I think this was addressed in pre-release 4: “The order of chat messages are now cryptographically verified”, specifically “This will be used for validating the context of chat messages for Player Reports”

**Comment by Nolij** [comment]
The only order verification I can see in the pre4 source is that messages now include a timestamp which is signed as part of the message so modifying the timestamp invalidates the signature. This shouldn't prevent what this mod does.
