### ISSUE TITLE
Private message workaround - inconsistency between LastSeen and report context

### ISSUE THREAD

**Issue by ylyxa** [nodusclient/gaslight#5]
From the gist, "For the last 5 players of which you've seen any messages, their last message's signature will be included."

Won't it conflict with the context in the report? The signature for the private message you send to yourself won't be in that `LastSeen` field (edit: and "Do you want to PVP?" will), hinting that the context is fake.

Conversely, perhaps you might deliberately put signatures of random messages in your own `LastSeen`, effectively making it look like any player reporting you is faking context?

**Comment by 0xAda** [comment]
thats a great idea, we'll put random signatures in last seen, the server doesn't check them so should make any report look fine
