### ISSUE TITLE
ability to change context

### ISSUE THREAD

**Issue by rafalohaki** [nodusclient/gaslight#6]
ability to change context was removed in other repo,
I would love to see that here
https://github.com/fxmorin/FabricatedChatReports/commit/1e74c8b8055d922b9e8400d913ec11621c29de50#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R6

**Comment by Roadhog360** [comment]
You can't, messages are signed and chain-signed now, so it's no longer possible because it invalidates the signature.
