### ISSUE TITLE
Allow fake completely reports

### ISSUE THREAD

**Issue by Danjhop4** [nodusclient/gaslight#8]
Allows users to make make fake messages with keys by making fake context if you can do it

**Comment by Roadhog360** [comment]
No, not possible. You can't make fake context out of nowhere, you have to have the message be sent to the server in some way.

**Comment by Nolij** [comment]
technically you could trick clients in to signing a modified message with the right timing, not sure if thatd be traceable on the report side though

**Comment by Roadhog360** [comment]
That's still a thing?

**Comment by 0xAda** [comment]
we're releasing our P=NP proof on thursday, this is coming immediately after
