### ISSUE TITLE
Forge supports?

### ISSUE THREAD

**Issue by IlyaTheSawmill** [nodusclient/gaslight#9]
There are nothing shows what loader can make this mod run, can it run with Forge? I don't use Fabric. If not, can you make one?

**Comment by hcesaropz** [comment]
[gaslight/gradle.properties](https://github.com/nodusclient/gaslight/blob/main/gradle.properties)

that's Fabric.

don't like that? be the first to port Gaslight to Forge!

(...ok tbh Forge is ridiculously hard to work with nowadays, please for the love of god just switch to Fabric)

**Comment by 0xAda** [comment]
skill issue
